add unit test for blob ref invalidation in union
This currently fails, since a table only keeps references to all runs in
of regular levels (using the LevelsCache).

      Exception: ErrBlobRefInvalid 80